### ISSUE TITLE
Karma for being Annoying idea

### ISSUE THREAD

**Issue by Canatopher** [Chrigi2486/CTModsLC#1]
Currently the mod targets spamming of the airhorn and clown horn, but the remote control is also an incredibly annoying item as it rapidly flickers the ship lights from anywhere. Could this item be added to the mod so that using it has a chance of killing you?
Additionally, a config that lets you adjust the chance of each item killing you would be nice too.

**Comment by Chrigi2486** [comment]
Thank you for your feedback!  
We have taken your ideas into consideration and have released a new update adding a config file and including the remote.  
The update should go live in the Thunderstore soon.  
Thanks for using our mods and supporting them with new ideas and we hope you continue enjoying them!  
Regards  
Christian and Tom
