### ISSUE TITLE
Cant drop an item that was held when they die

### ISSUE THREAD

**Issue by NoahE07** [Chrigi2486/CTModsLC#3]
Mod: Go out with a Bang

An item can become stuck in your inventory forever, stopping you from switching to another item or executing an action if
1. a person dies with the item in their hand
2. a player brings that item back into the ship
3. the team leaves that planet
4. someone picks up that item (say to sell it)
mod list in files and image that helped me realize its this mod uploaded

only fix found:
dont pick up items dead players drop or host leaving and restarting the save
![image](https://github.com/Chrigi2486/CTModsLC/assets/155043208/da795916-82ad-4ff0-9ed0-1869edde4e2c)
[FAFO_1703738324184.zip](https://github.com/Chrigi2486/CTModsLC/files/13783335/FAFO_1703738324184.zip)

**Comment by Chrigi2486** [comment]
Thank you for reaching out with this issue!  
  
Could you please test this without the LethalExpansion Mod installed and reach back again with the results, as I have a suspicion that it may have a conflict with our mod?  
  
Currently we are both on holiday with exams coming up, so at the moment it isn't possible for us to test or fix any issues.  

Thank you for using our mods and providing feedback!  
Regards  
Christian and Tom

**Comment by NoahE07** [comment]
I will! sadly that will have to be tomorrow as my friends got off for the night, I will update as soon as I can

**Comment by Chrigi2486** [comment]
I've taken a look at it and seems to be an issue with LethalExpansion when removing items from a mine which has already exploded.  
We can look into to if we don't despawn the mine properly, but I'm not sure if the issue is on our side.

**Comment by NoahE07** [comment]
Sorry about not getting back to you! My buddies decided they wanted to just
redo our mod pack and neither mods were included so we never got to testing
it, glad you figured it out!
